kind: ConfigMap
apiVersion: v1
data:
  prometheus-config: |-
    scrape_configs:
    - job_name: cluster-autoscaler
      follow_redirects: false
      sample_limit: 200
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - {{ .Values.global.commonGlobals.Customer.Namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app, __meta_kubernetes_pod_container_name]
        action: keep
        regex: cluster-autoscaler;cluster-autoscaler
      - source_labels: [__meta_kubernetes_pod_annotation_aks_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_aks_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_aks_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.*)
        target_label: pod
        action: replace
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: process_start_time_seconds|rest_client_requests_total|cluster_autoscaler_((last_activity|cluster_safe_to_autoscale|failed_scale_ups_total|scale_down_in_cooldown|scaled_up_nodes_total|unneeded_nodes_count|unschedulable_pods_count|nodes_count))|cloudprovider_azure_api_request_(errors|duration_seconds_(bucket|count))
        action: keep
    - job_name: kube-controller-manager
      sample_limit: 300
      follow_redirects: false
      scheme: https
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - {{ .Values.global.commonGlobals.Customer.Namespace }}
      tls_config:
        ca_file: /etc/kubernetes/secrets/ca.pem
        cert_file: /etc/kubernetes/secrets/client.pem
        key_file: /etc/kubernetes/secrets/client-key.pem
        insecure_skip_verify: true
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_k8s_app, __meta_kubernetes_pod_container_name]
        action: keep
        regex: kube-controller-manager;kube-controller-manager
      - source_labels: [__meta_kubernetes_pod_annotation_aks_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_aks_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_aks_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.*)
        target_label: pod
        action: replace
      metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: cloudprovider_azure_(api_(request_throttled_count|request_duration_seconds_count|request_(latency|duration_seconds)_bucket|op_duration_seconds_bucket))|rest_client_requests_total|process_start_time_seconds
    - job_name: kube-scheduler
      sample_limit: 5
      follow_redirects: false
      scheme: https
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - {{ .Values.global.commonGlobals.Customer.Namespace }}
      tls_config:
        ca_file: /etc/kubernetes/secrets/ca.pem
        cert_file: /etc/kubernetes/secrets/client.pem
        key_file: /etc/kubernetes/secrets/client-key.pem
        insecure_skip_verify: true
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_k8s_app, __meta_kubernetes_pod_container_name]
        action: keep
        regex: kube-scheduler;kube-scheduler
      - source_labels: [__meta_kubernetes_pod_annotation_aks_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_aks_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_aks_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.*)
        target_label: pod
        action: replace
      metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: process_start_time_seconds
    - job_name: etcd
      sample_limit: 1000
      follow_redirects: false
      scheme: https
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.global.commonGlobals.Customer.Namespace }}
      tls_config:
        ca_file: /etc/kubernetes/secrets/etcd-client-ca.crt
        cert_file: /etc/kubernetes/secrets/etcd-client.crt
        key_file: /etc/kubernetes/secrets/etcd-client.key
        insecure_skip_verify: true
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app, __meta_kubernetes_pod_container_port_number]
        action: keep
        regex: etcd;2379
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.*)
        target_label: pod
        action: replace
      metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: etcd_(server_(has_leader|is_leader|id|leader_changes_seen_total|proposals_(committed_total|applied_total|pending|failed_total)|quota_backend_bytes)|disk_(wal_fsync|backend_commit|backend_defrag)_duration_seconds_bucket|network_(peer_round_trip_time_seconds_bucket|(client_grpc|peer)_(received|sent)_bytes_total)|mvcc_db_total_size_in_(bytes|use_in_bytes))
    - job_name: etcd-backup
      sample_limit: 56
      follow_redirects: false
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - {{ .Values.global.commonGlobals.Customer.Namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app, __meta_kubernetes_pod_container_name]
        action: keep
        regex: etcd_backup_tool;backup
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+)(?::\d+)?
        replacement: ${1}:19999
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.*)
        target_label: pod
        action: replace
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: etcd_operator_cluster_(revocable_sas_token_time_to_expire|cluster_defragment_failed|cluster_backup_failed|cluster_alarm_number)
        action: keep
    - job_name: etcd-backup-https
      sample_limit: 56
      follow_redirects: false
      scheme: https
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - {{ .Values.global.commonGlobals.Customer.Namespace }}
      tls_config:
        # TODO: switch to /etc/kubernetes/secrets/backup-client-ca.crt once all clusters have backup certs
        ca_file: /etc/kubernetes/secrets/etcd-client-ca.crt
        insecure_skip_verify: true
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app, __meta_kubernetes_service_name]
        action: keep
        regex: etcd;etcd-(.+)-backup-sidecar
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+)(?::\d+)?
        replacement: ${1}:39999
        target_label: __address__
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: etcd_operator_cluster_(defragment_failed|cluster_alarm_number|cluster_backup_failed|revocable_sas_token_time_to_expire|abs_unauthorized_error|kubernetes_resource_size|snapshot_size|key_values_counts|key_topn_keys_by_size|key_topn_keys_by_version|snapshot_analysis_cost_seconds)
        action: keep
      # drop unnecessary labels to reduce metric cardinality
      - action: labeldrop
        regex: instance
    - job_name: etcd-operator
      sample_limit: 695
      follow_redirects: false
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - {{ .Values.global.commonGlobals.Customer.Namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_overlay_app]
        action: keep
        regex: etcd-operator
      - source_labels: [__address__]
        action: replace
        regex: ([^:]+)(?::\d+)?
        replacement: ${1}:8080
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_name]
        regex: (.*)
        target_label: pod
        action: replace
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: etcd_operator_cluster_(ready_member_size|goal_member_size|cluster_cert_time_to_expire|cluster_ca_time_to_expire|cluster_sas_token_time_to_expire|reconcile_failed|disaster_recovery_happened|cluster_defragment_failed|cluster_backup_failed|cluster_alarm_number)
        action: keep
    - job_name: kube-apiserver
      scrape_interval: 30s
      label_limit: 63
      label_name_length_limit: 511
      label_value_length_limit: 1023
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.global.commonGlobals.Customer.Namespace }}
      scheme: https
      tls_config:
        ca_file: /etc/kubernetes/secrets/ca.pem
        insecure_skip_verify: true
      bearer_token_file: /etc/kubernetes/secrets/token
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_k8s_app
        - __meta_kubernetes_pod_container_name
        action: keep
        regex: kube-apiserver;kube-apiserver
      metric_relabel_configs:
      - source_labels:
        - __name__
        action: keep
        regex: "|apiserver_request_total|apiserver_cache_list_fetched_objects_total|apiserver_cache_list_returned_objects_total|apiserver_flowcontrol_demand_seats_average|apiserver_flowcontrol_current_limit_seats|apiserver_flowcontrol_rejected_requests_total|apiserver_request_sli_duration_seconds|process_start_time_seconds|apiserver_request_duration_seconds|apiserver_storage_fetched_objects_total|apiserver_storage_list_returned_objects_total|apiserver_current_inflight_requests"   
metadata:
  name: ama-metrics-prometheus-config
  namespace: {{ .Values.global.commonGlobals.Customer.Namespace }}