apiVersion: v1
kind: ConfigMap
data:
  schema-version:
    v1
  config-version:
    ver1
  prometheus-collector-settings: |-
    default_metric_account_name = "default"
    cluster_alias = ""
    kubelet = false
    coredns = false
    cadvisor = false
    kubeproxy = false
    apiserver = false
    kubestate = false
    nodeexporter = false
    windowsexporter = false
    windowskubeproxy = false
    kappiebasic = false
    prometheuscollectorhealth = true
    kube-apiserver = true
    cluster-autoscaler = true
    kube-scheduler = true
    kube-controller-manager = true
    etcd = true
  default-targets-metrics-keep-list: |-
   kubelet = ""
    coredns = ""
    cadvisor = ""
    kubeproxy = ""
    apiserver = ""
    kubestate = ""
    nodeexporter = ""
    windowsexporter = ""
    windowskubeproxy = ""
    podannotations = ""
    kappiebasic = ""
    kube-apiserver = ""
    cluster-autoscaler = ""
    kube-scheduler = ""
    kube-controller-manager = ""
    etcd = ""
    minimalingestionprofile = true
  debug-mode: |-
    enabled = true
  default-targets-scrape-interval-settings: |-
    kubelet = "30s"
    coredns = "30s"
    cadvisor = "30s"
    kubeproxy = "30s"
    apiserver = "30s"
    kubestate = "30s"
    nodeexporter = "30s"
    windowsexporter = "30s"
    windowskubeproxy = "30s"
    kappiebasic = "30s"
    prometheuscollectorhealth = "30s"
    podannotations = "30s"
    kube-apiserver = "30s"
    cluster-autoscaler = "30s"
    kube-scheduler = "30s"
    kube-controller-manager = "30s"
    etcd = "30s"
metadata:
  name: ama-metrics-settings-configmap-ccp
  namespace: {{ .Values.global.commonGlobals.Customer.Namespace }}