apiVersion: v1
kind: Secret
metadata:
  name: kubeconfig-file
stringData:
  kubeconfig.yaml: |-
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data:  <redacted>
        server: https://dakydddev--dakydddev-82acd5-rzqniqhl.hcp.australiasoutheast.azmk8s.io:443
      name: dakydddev-winnpm
    contexts:
    - context:
        cluster: dakydddev-winnpm
        user: clusterUser_dakydddev_dakydddev-winnpm
      name: dakydddev-winnpm
    current-context: dakydddev-winnpm
    kind: Config
    preferences: {}
    users:
    - name: clusterUser_dakydddev_dakydddev-winnpm
      user:
        client-certificate-data:  <redacted>